language: node_js
node_js:
  - v0.10
  - v0.11
  - v0.12
  - v4.2.4
before_script:
  - curl -sSkL https://git.io/perl-install | bash -s ./perl
  - ./perl/bin/cpanm Text::Xslate
  - export PATH=$PATH:$PWD/perl/bin
  - export PERL5LIB=$PERL5LIB:$PWD/perl/lib/5.22.1
